### PR TITLE
feat: Injectable BitmapDescriptorFactory

### PR DESCRIPTION
**Pull request by amay077**
Thanks for your great implementation of caching BitmapDescriptorFactory.

But I have some change requests.

### 1. Move CachingNativeBitmapDescriptorFactory to app side.

I hope everyone can customize BitmapDescriptorFactory in each apps.

* ``IBitmapDescriptorFactory`` is common interface
* ``PlatformConfig`` and ``PlatformConfig.BitmapDescriptorFactory`` can overrides ``BitmapDescriptorFactory`` default implementation
* Add parameter "config" to ``Xamarin.FormsGoogleMaps.Init``

### 2.  Change BitmapDescriptor.Id type to ``string``

I think ``Id`` is not always number.

### 3. Make public to BitmapDescriptor properties

If you implement custom BitmapDescriptorFactory then need gets some BitmapDescriptor properties.

----

If you approve this PR, merge and please [send PR](https://github.com/amay077/Xamarin.Forms.GoogleMaps/pulls) to me.
Then, I will merge it.

### CODE REVIEW

**Comment by Matiszak** [comment]
Great job with that Factory and PlatformConfig. I've got one question:
What is the purpose of injecting Func<IBitmapDescriptorFactory> into logics ? Maybe remove this indirection and move duplicated 
      ?? DefaultBitmapDescriptorFactory.Instance
 into MapRenderer ?

If we reaolve that I will test it(including memory tests) and if everything works  I'll make PR to you. Later this week I'll start implementing iOS solution as well and test it on friend's iphone.

Writing from phone so sorry for ugly formatting.

**Comment by amay077** [comment]
> What is the purpose of injecting Func into logics ?

It is no need, so I fixed it.
Thanks.

https://github.com/Matiszak/Xamarin.Forms.GoogleMaps/pull/1/commits/07bc2a9d1a0d16b9c9ee402202a36f36365e1663

**Comment by amay077** [comment]
Thanks for your merging.

And Please send PR to [my repo](https://github.com/amay077/Xamarin.Forms.GoogleMaps/pulls) .
I will merge immediately.
Because I hope join you to [contributors](https://github.com/amay077/Xamarin.Forms.GoogleMaps/graphs/contributors).

**Comment by Matiszak** [comment]
I couldn't test because droid sample seems to be not working properely - I counldn't see any pin, any objects on all demos. I'll debug it this evening and make PR in the night :)

**Pull request merged**
